version: '2'
services:
  web:
       build:
               context: .
               dockerfile: Dockerfile
       container_name: In-Gro
       volumes:
          - ./In-Gro:/var/www/html/
       depends_on: 
         - db  
       ports:
         - 8008:80
  db:
          container_name: mysqli-In_Gro
          image: mysql:latest
          command: --default-authentication-plugin=mysql_native_password
          restart: always  
          volumes:
             - ./In-Gro/database/grocery2.sql:/var/lib/mysql
          environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: grocery2
            MYSQL_USER: root
            MYSQL_PASSWORD: 
          ports:
           - 8080:8080 
